# Generated by Django 5.0.9 on 2024-09-28 13:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_remove_blogpost_title_blogpost_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="title",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=models.TextField(),
        ),
    ]
